In [2]:
from sklearn.preprocessing import MinMaxScaler
 
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
 

In [3]:
#不太熟悉numpy的小伙伴，能够判断data的结构吗？
#如果换成表是什么样子？
import pandas as pd
pd.DataFrame(data)
 

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [4]:
#实现归一化(每一列的运算！！！！！按照公式！)
scaler = MinMaxScaler()                             #实例化

#以下两部可以用一个scaler.fit_transform(data)代替。
scaler = scaler.fit(data)                           #fit训练，在这里本质是生成min(x)和max(x)
result = scaler.transform(data)                     #通过接口导出结果
result
 

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [6]:
result_ = scaler.fit_transform(data)                #训练和导出结果一步达成
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [7]:
scaler.inverse_transform(result)                    #将归一化后的结果逆转
 

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [1]:
#使用MinMaxScaler的参数feature_range实现将数据归一化到[0,1]以外的范围中
 
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler(feature_range=[5,10])         #依然实例化

result = scaler.fit_transform(data)                 #fit_transform一步导出结果
result
 
#当X中的特征数量非常多的时候，fit会报错并表示，数据量太大了我计算不了
#此时使用partial_fit作为训练接口
#scaler = scaler.partial_fit(data)

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

### 当数据(x)按均值(μ)中心化后，再按标准差(σ)缩放，数据就会服从为均值为0，方差为1的正态分布（即标准正态分布），而这个过程，就叫做数据标准化(Standardization，又称Z-score normalization)

In [15]:
from sklearn.preprocessing import StandardScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
pd.DataFrame(data)#两列：代表有两个特征！

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [11]:
scaler = StandardScaler()                           #实例化
scaler.fit(data)                                    #fit，本质是生成均值和方差

StandardScaler()

In [12]:
scaler.mean_                                        #查看均值的属性mean_：有两列，因为有两个特征

array([-0.125,  9.   ])

In [16]:
scaler.var_                                         #查看方差的属性var_：有两列，因为有两个特征

array([ 0.546875, 35.      ])

In [ ]:
x_std = scaler.transform(data)                      #通过接口导出结果：通过scaler.transform之后就变成了符合标准正态分布的数组。

### 查看转化后的均值和方差

In [17]:
x_std.mean()                                        #导出的结果是一个数组，用mean()查看均值

0.0

In [18]:
x_std.std()                                         #用std()查看方差
 

1.0

### 当然了，和归一化一样，标准化也有一步生成和逆变换！！！！

In [10]:
scaler.fit_transform(data)                          #使用fit_transform(data)一步达成结果
scaler.inverse_transform(x_std)                  #使用inverse_transform逆转标准

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])